01 - Componentes MVC Y aplicando seguridad al Website/NetCore.Fundamentals.OIC/NetCore.Fundamentals.OIC.Client.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace NetCore.Fundamentals.OIC.Client.Web.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login() => Challenge(new AuthenticationProperties { RedirectUri = "/" });
    }
}

01 - Componentes MVC Y aplicando seguridad al Website/NetCore.Fundamentals.OIC/NetCore.Fundamentals.OIC.Client.Web/Controllers/ConferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NetCore.Fundamentals.OIC.Client.Web.Infrastructure.Agents.Conference;
using NetCore.Fundamentals.OIC.Data.Model;

namespace NetCore.Fundamentals.OIC.Client.Web.Controllers
{
    public class ConferenceController : Controller
    {
        private readonly IConferenceAgent _conferenceAgent;
        public ConferenceController(IConferenceAgent conferenceAgent)
        {
            _conferenceAgent = conferenceAgent;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Organizer - Conference Overview";
            return View(await _conferenceAgent.GetAllConferences());
        }
        public IActionResult Add()
        {
            ViewBag.Title = "Organizer - Add Conference";
            return View(new ConferenceModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(ConferenceModel model)
        {
            if (ModelState.IsValid)
                await _conferenceAgent.AddConference(model);

            return RedirectToAction("Index");
        }
    }
}

01 - Componentes MVC Y aplicando seguridad al Website/NetCore.Fundamentals.OIC/NetCore.Fundamentals.OIC.Client.Web/Controllers/ProposalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NetCore.Fundamentals.OIC.Client.Web.Infrastructure.Agents.Proposal;
using NetCore.Fundamentals.OIC.Data.Model;

namespace NetCore.Fundamentals.OIC.Client.Web.Controllers
{
    public class ProposalController : Controller
    {
        private readonly IProposalAgent _proposalAgent;
        public ProposalController(IProposalAgent proposalAgent)
        {
            _proposalAgent = proposalAgent;
        }
        public async Task<IActionResult> Index(int conferenceId)
        {
            ViewBag.Title = $"Speaker - Proposals For Conference {conferenceId}";
            ViewBag.ConferenceId = conferenceId;

            return View(await _proposalAgent.GetAllProposalsForConference(conferenceId));
        }

        public IActionResult AddProposal(int conferenceId)
        {
            ViewBag.Title = "Speaker - Add Proposal";
            return View(new ProposalModel { ConferenceId = conferenceId });
        }

        [HttpPost]
        public async Task<IActionResult> AddProposal(ProposalModel proposal)
        {
            if (ModelState.IsValid)
                await _proposalAgent.AddProposal(proposal);
            return RedirectToAction("Index", new { conferenceId = proposal.ConferenceId });
        }

        public async Task<IActionResult> Approve(int proposalId)
        {
            var proposal = await _proposalAgent.ApproveProposal(proposalId);
            return RedirectToAction("Index", new { conferenceId = proposal.ConferenceId });
        }
    }
}

01 - Componentes MVC Y aplicando seguridad al Website/NetCore.Fundamentals.OIC/NetCore.Fundamentals.OIC.Client.Web/Views/Conference/Add.cshtml
@model NetCore.Fundamentals.OIC.Data.Model.ConferenceModel
<form asp-action="Add">
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Name"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Name" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Location"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Location" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Start"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" type="date" asp-for="Start" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-4">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

01 - Componentes MVC Y aplicando seguridad al Website/NetCore.Fundamentals.OIC/NetCore.Fundamentals.OIC.Client.Web/Views/Conference/Index.cshtml
@model IEnumerable<NetCore.Fundamentals.OIC.Data.Model.ConferenceModel>
<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Start of event</th>
                <th>Attendees</th>
                <th>Actions</th>
            </tr>
            @foreach (var conference in Model)
            {
                <tr>
                    <td>@conference.Name</td>
                    <td>@conference.Location</td>
                    <td>@conference.Start.ToString("ddd d MMM")</td>
                    <td>@conference.AttendeeCount</td>
                    <td>
                        <a asp-controller="Proposal" asp-action="Index" asp-route-conferenceId="@conference.ConferenceId">Proposals</a>
                    </td>
                </tr>
            }
        </table>
        <a asp-action="Add">Add</a>

    </div>
</div>

@if (User.Identity.IsAuthenticated)
{
    <table class="table table-sm">
        @foreach (var claim in User.Claims)
        {
            <tr>
                <td>@claim.Type</td>
                <td>@claim.Value</td>
            </tr>
        }
    </table>
}

01 - Componentes MVC Y aplicando seguridad al Website/NetCore.Fundamentals.OIC/NetCore.Fundamentals.OIC.Client.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCore.Fundamentals.OIC.Client.Web</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
   
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <img src="~/img/logo.png" style="max-width:100%" />
            </div>
            <div class="col-md-9 titlecol">
                <span class="title">@ViewBag.Title</span>
            </div>
        </div>
        <div>
            @RenderBody()
        </div>
    </div>

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>